name: Android CI

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run tests
      run: ./gradlew :app:testDebugUnitTest
    
    - name: Build debug APK
      run: ./gradlew assembleDebug
    
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
    
    # Release build (only on tags)
    - name: Decode keystore
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-keystore.jks
    
    - name: Build signed release APK
      if: startsWith(github.ref, 'refs/tags/v')
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_FILE: ${{ github.workspace }}/release-keystore.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Clean up keystore
      if: always() && startsWith(github.ref, 'refs/tags/v')
      run: rm -f release-keystore.jks
